# fly.toml app configuration file generated for dammi-server-wild-sea-4789 on 2025-08-24T14:15:39+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dammi-server-wild-sea-4789'
primary_region = 'bom'

[build]
  builder = "paketobuildpacks/builder-jammy-full"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'